//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NettapotekForm.UtlevererWebService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class AppRecFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M9_12 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M9_11 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M9_22 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M9_21 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class MV : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M9_2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M9_1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M10 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M9_4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M9_3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M25_3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M27_2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M27_1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class AppRec : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M25_2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/")]
    public partial class M3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", ConfigurationName="UtlevererWebService.UtlevererWeb")]
    public interface UtlevererWeb {
        
        // CODEGEN: Generating message contract since the operation UtlevererWebService_m3 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="M3", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_12))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_11))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_22))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_21))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_4))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_2))]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m3Response UtlevererWebService_m3(NettapotekForm.UtlevererWebService.UtlevererWebService_m3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="M3", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m3Response")]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m3Response> UtlevererWebService_m3Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m3Request request);
        
        // CODEGEN: Generating message contract since the operation UtlevererWebService_verify is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Verify", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_verifyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_12))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_11))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_22))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_21))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_4))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_2))]
        NettapotekForm.UtlevererWebService.UtlevererWebService_verifyResponse UtlevererWebService_verify(NettapotekForm.UtlevererWebService.UtlevererWebService_verifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Verify", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_verifyResponse")]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_verifyResponse> UtlevererWebService_verifyAsync(NettapotekForm.UtlevererWebService.UtlevererWebService_verifyRequest request);
        
        // CODEGEN: Generating message contract since the operation UtlevererWebService_m10 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="M10", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m10Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_12))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_11))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_22))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_21))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_4))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_2))]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m10Response UtlevererWebService_m10(NettapotekForm.UtlevererWebService.UtlevererWebService_m10Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="M10", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m10Response")]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m10Response> UtlevererWebService_m10Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m10Request request);
        
        // CODEGEN: Generating message contract since the operation UtlevererWebService_m27_1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="M27_1", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m27_1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(NettapotekForm.UtlevererWebService.AppRecFault), Action="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m27_1/Fault/AppRecFault", Name="AppRecFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_12))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_11))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_22))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_21))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_4))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_2))]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Response UtlevererWebService_m27_1(NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="M27_1", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m27_1Response")]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Response> UtlevererWebService_m27_1Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Request request);
        
        // CODEGEN: Generating message contract since the operation UtlevererWebService_m9_11 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="M9_11", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m9_11Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(NettapotekForm.UtlevererWebService.AppRecFault), Action="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m9_11/Fault/AppRecFault", Name="AppRecFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_12))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_11))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_22))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_21))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_4))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_2))]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Response UtlevererWebService_m9_11(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="M9_11", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m9_11Response")]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Response> UtlevererWebService_m9_11Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Request request);
        
        // CODEGEN: Generating message contract since the operation UtlevererWebService_m25_2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="M25_2", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m25_2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_12))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_11))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_22))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_21))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_4))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_2))]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Response UtlevererWebService_m25_2(NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="M25_2", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m25_2Response")]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Response> UtlevererWebService_m25_2Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Request request);
        
        // CODEGEN: Generating message contract since the operation UtlevererWebService_m25_3 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="M25_3", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m25_3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_12))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_11))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_22))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_21))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_4))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_2))]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Response UtlevererWebService_m25_3(NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="M25_3", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m25_3Response")]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Response> UtlevererWebService_m25_3Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Request request);
        
        // CODEGEN: Generating message contract since the operation UtlevererWebService_m9_3 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="M9_3", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m9_3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_12))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_11))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_22))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_21))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_4))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_2))]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Response UtlevererWebService_m9_3(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="M9_3", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m9_3Response")]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Response> UtlevererWebService_m9_3Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Request request);
        
        // CODEGEN: Generating message contract since the operation UtlevererWebService_m9_21 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="M9_21", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m9_21Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(NettapotekForm.UtlevererWebService.AppRecFault), Action="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m9_21/Fault/AppRecFault", Name="AppRecFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_12))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_11))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_22))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_21))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_4))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_2))]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Response UtlevererWebService_m9_21(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="M9_21", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m9_21Response")]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Response> UtlevererWebService_m9_21Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Request request);
        
        // CODEGEN: Generating message contract since the operation UtlevererWebService_m9_1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="M9_1", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m9_1Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_12))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_11))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_22))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_21))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_4))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_3))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M25_2))]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Response UtlevererWebService_m9_1(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="M9_1", ReplyAction="http://utleverer.webservices.reseptformidleren.ergo.no/UtlevererWeb/UtlevererWebS" +
            "ervice_m9_1Response")]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Response> UtlevererWebService_m9_1Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M3 M3Element;
        
        public UtlevererWebService_m3Request() {
        }
        
        public UtlevererWebService_m3Request(NettapotekForm.UtlevererWebService.M3 M3Element) {
            this.M3Element = M3Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.AppRec AppRecElement;
        
        public UtlevererWebService_m3Response() {
        }
        
        public UtlevererWebService_m3Response(NettapotekForm.UtlevererWebService.AppRec AppRecElement) {
            this.AppRecElement = AppRecElement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_verifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.MV MVElement;
        
        public UtlevererWebService_verifyRequest() {
        }
        
        public UtlevererWebService_verifyRequest(NettapotekForm.UtlevererWebService.MV MVElement) {
            this.MVElement = MVElement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_verifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.AppRec AppRecElement;
        
        public UtlevererWebService_verifyResponse() {
        }
        
        public UtlevererWebService_verifyResponse(NettapotekForm.UtlevererWebService.AppRec AppRecElement) {
            this.AppRecElement = AppRecElement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m10Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M10 M10Element;
        
        public UtlevererWebService_m10Request() {
        }
        
        public UtlevererWebService_m10Request(NettapotekForm.UtlevererWebService.M10 M10Element) {
            this.M10Element = M10Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m10Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.AppRec AppRecElement;
        
        public UtlevererWebService_m10Response() {
        }
        
        public UtlevererWebService_m10Response(NettapotekForm.UtlevererWebService.AppRec AppRecElement) {
            this.AppRecElement = AppRecElement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m27_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M27_1 M27_1Element;
        
        public UtlevererWebService_m27_1Request() {
        }
        
        public UtlevererWebService_m27_1Request(NettapotekForm.UtlevererWebService.M27_1 M27_1Element) {
            this.M27_1Element = M27_1Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m27_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M27_2 M27_2Element;
        
        public UtlevererWebService_m27_1Response() {
        }
        
        public UtlevererWebService_m27_1Response(NettapotekForm.UtlevererWebService.M27_2 M27_2Element) {
            this.M27_2Element = M27_2Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m9_11Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M9_11 M9_11Element;
        
        public UtlevererWebService_m9_11Request() {
        }
        
        public UtlevererWebService_m9_11Request(NettapotekForm.UtlevererWebService.M9_11 M9_11Element) {
            this.M9_11Element = M9_11Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m9_11Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M9_12 M9_12Element;
        
        public UtlevererWebService_m9_11Response() {
        }
        
        public UtlevererWebService_m9_11Response(NettapotekForm.UtlevererWebService.M9_12 M9_12Element) {
            this.M9_12Element = M9_12Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m25_2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M25_2 M25_2Element;
        
        public UtlevererWebService_m25_2Request() {
        }
        
        public UtlevererWebService_m25_2Request(NettapotekForm.UtlevererWebService.M25_2 M25_2Element) {
            this.M25_2Element = M25_2Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m25_2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.AppRec AppRecElement;
        
        public UtlevererWebService_m25_2Response() {
        }
        
        public UtlevererWebService_m25_2Response(NettapotekForm.UtlevererWebService.AppRec AppRecElement) {
            this.AppRecElement = AppRecElement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m25_3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M25_3 M25_3Element;
        
        public UtlevererWebService_m25_3Request() {
        }
        
        public UtlevererWebService_m25_3Request(NettapotekForm.UtlevererWebService.M25_3 M25_3Element) {
            this.M25_3Element = M25_3Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m25_3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.AppRec AppRecElement;
        
        public UtlevererWebService_m25_3Response() {
        }
        
        public UtlevererWebService_m25_3Response(NettapotekForm.UtlevererWebService.AppRec AppRecElement) {
            this.AppRecElement = AppRecElement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m9_3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M9_3 M9_3Element;
        
        public UtlevererWebService_m9_3Request() {
        }
        
        public UtlevererWebService_m9_3Request(NettapotekForm.UtlevererWebService.M9_3 M9_3Element) {
            this.M9_3Element = M9_3Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m9_3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M9_4 M9_4Element;
        
        public UtlevererWebService_m9_3Response() {
        }
        
        public UtlevererWebService_m9_3Response(NettapotekForm.UtlevererWebService.M9_4 M9_4Element) {
            this.M9_4Element = M9_4Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m9_21Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M9_21 M9_21Element;
        
        public UtlevererWebService_m9_21Request() {
        }
        
        public UtlevererWebService_m9_21Request(NettapotekForm.UtlevererWebService.M9_21 M9_21Element) {
            this.M9_21Element = M9_21Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m9_21Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M9_22 M9_22Element;
        
        public UtlevererWebService_m9_21Response() {
        }
        
        public UtlevererWebService_m9_21Response(NettapotekForm.UtlevererWebService.M9_22 M9_22Element) {
            this.M9_22Element = M9_22Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m9_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M9_1 M9_1Element;
        
        public UtlevererWebService_m9_1Request() {
        }
        
        public UtlevererWebService_m9_1Request(NettapotekForm.UtlevererWebService.M9_1 M9_1Element) {
            this.M9_1Element = M9_1Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtlevererWebService_m9_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://utleverer.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.UtlevererWebService.M9_2 M9_2Element;
        
        public UtlevererWebService_m9_1Response() {
        }
        
        public UtlevererWebService_m9_1Response(NettapotekForm.UtlevererWebService.M9_2 M9_2Element) {
            this.M9_2Element = M9_2Element;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UtlevererWebChannel : NettapotekForm.UtlevererWebService.UtlevererWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtlevererWebClient : System.ServiceModel.ClientBase<NettapotekForm.UtlevererWebService.UtlevererWeb>, NettapotekForm.UtlevererWebService.UtlevererWeb {
        
        public UtlevererWebClient() {
        }
        
        public UtlevererWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtlevererWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtlevererWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtlevererWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m3Response NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m3(NettapotekForm.UtlevererWebService.UtlevererWebService_m3Request request) {
            return base.Channel.UtlevererWebService_m3(request);
        }
        
        public NettapotekForm.UtlevererWebService.AppRec UtlevererWebService_m3(NettapotekForm.UtlevererWebService.M3 M3Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m3Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m3Request();
            inValue.M3Element = M3Element;
            NettapotekForm.UtlevererWebService.UtlevererWebService_m3Response retVal = ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m3(inValue);
            return retVal.AppRecElement;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m3Response> NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m3Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m3Request request) {
            return base.Channel.UtlevererWebService_m3Async(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m3Response> UtlevererWebService_m3Async(NettapotekForm.UtlevererWebService.M3 M3Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m3Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m3Request();
            inValue.M3Element = M3Element;
            return ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.UtlevererWebService.UtlevererWebService_verifyResponse NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_verify(NettapotekForm.UtlevererWebService.UtlevererWebService_verifyRequest request) {
            return base.Channel.UtlevererWebService_verify(request);
        }
        
        public NettapotekForm.UtlevererWebService.AppRec UtlevererWebService_verify(NettapotekForm.UtlevererWebService.MV MVElement) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_verifyRequest inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_verifyRequest();
            inValue.MVElement = MVElement;
            NettapotekForm.UtlevererWebService.UtlevererWebService_verifyResponse retVal = ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_verify(inValue);
            return retVal.AppRecElement;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_verifyResponse> NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_verifyAsync(NettapotekForm.UtlevererWebService.UtlevererWebService_verifyRequest request) {
            return base.Channel.UtlevererWebService_verifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_verifyResponse> UtlevererWebService_verifyAsync(NettapotekForm.UtlevererWebService.MV MVElement) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_verifyRequest inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_verifyRequest();
            inValue.MVElement = MVElement;
            return ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_verifyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m10Response NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m10(NettapotekForm.UtlevererWebService.UtlevererWebService_m10Request request) {
            return base.Channel.UtlevererWebService_m10(request);
        }
        
        public NettapotekForm.UtlevererWebService.AppRec UtlevererWebService_m10(NettapotekForm.UtlevererWebService.M10 M10Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m10Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m10Request();
            inValue.M10Element = M10Element;
            NettapotekForm.UtlevererWebService.UtlevererWebService_m10Response retVal = ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m10(inValue);
            return retVal.AppRecElement;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m10Response> NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m10Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m10Request request) {
            return base.Channel.UtlevererWebService_m10Async(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m10Response> UtlevererWebService_m10Async(NettapotekForm.UtlevererWebService.M10 M10Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m10Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m10Request();
            inValue.M10Element = M10Element;
            return ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m10Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Response NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m27_1(NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Request request) {
            return base.Channel.UtlevererWebService_m27_1(request);
        }
        
        public NettapotekForm.UtlevererWebService.M27_2 UtlevererWebService_m27_1(NettapotekForm.UtlevererWebService.M27_1 M27_1Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Request();
            inValue.M27_1Element = M27_1Element;
            NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Response retVal = ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m27_1(inValue);
            return retVal.M27_2Element;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Response> NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m27_1Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Request request) {
            return base.Channel.UtlevererWebService_m27_1Async(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Response> UtlevererWebService_m27_1Async(NettapotekForm.UtlevererWebService.M27_1 M27_1Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m27_1Request();
            inValue.M27_1Element = M27_1Element;
            return ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m27_1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Response NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m9_11(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Request request) {
            return base.Channel.UtlevererWebService_m9_11(request);
        }
        
        public NettapotekForm.UtlevererWebService.M9_12 UtlevererWebService_m9_11(NettapotekForm.UtlevererWebService.M9_11 M9_11Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Request();
            inValue.M9_11Element = M9_11Element;
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Response retVal = ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m9_11(inValue);
            return retVal.M9_12Element;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Response> NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m9_11Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Request request) {
            return base.Channel.UtlevererWebService_m9_11Async(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Response> UtlevererWebService_m9_11Async(NettapotekForm.UtlevererWebService.M9_11 M9_11Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m9_11Request();
            inValue.M9_11Element = M9_11Element;
            return ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m9_11Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Response NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m25_2(NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Request request) {
            return base.Channel.UtlevererWebService_m25_2(request);
        }
        
        public NettapotekForm.UtlevererWebService.AppRec UtlevererWebService_m25_2(NettapotekForm.UtlevererWebService.M25_2 M25_2Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Request();
            inValue.M25_2Element = M25_2Element;
            NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Response retVal = ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m25_2(inValue);
            return retVal.AppRecElement;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Response> NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m25_2Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Request request) {
            return base.Channel.UtlevererWebService_m25_2Async(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Response> UtlevererWebService_m25_2Async(NettapotekForm.UtlevererWebService.M25_2 M25_2Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m25_2Request();
            inValue.M25_2Element = M25_2Element;
            return ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m25_2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Response NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m25_3(NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Request request) {
            return base.Channel.UtlevererWebService_m25_3(request);
        }
        
        public NettapotekForm.UtlevererWebService.AppRec UtlevererWebService_m25_3(NettapotekForm.UtlevererWebService.M25_3 M25_3Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Request();
            inValue.M25_3Element = M25_3Element;
            NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Response retVal = ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m25_3(inValue);
            return retVal.AppRecElement;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Response> NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m25_3Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Request request) {
            return base.Channel.UtlevererWebService_m25_3Async(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Response> UtlevererWebService_m25_3Async(NettapotekForm.UtlevererWebService.M25_3 M25_3Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m25_3Request();
            inValue.M25_3Element = M25_3Element;
            return ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m25_3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Response NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m9_3(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Request request) {
            return base.Channel.UtlevererWebService_m9_3(request);
        }
        
        public NettapotekForm.UtlevererWebService.M9_4 UtlevererWebService_m9_3(NettapotekForm.UtlevererWebService.M9_3 M9_3Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Request();
            inValue.M9_3Element = M9_3Element;
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Response retVal = ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m9_3(inValue);
            return retVal.M9_4Element;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Response> NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m9_3Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Request request) {
            return base.Channel.UtlevererWebService_m9_3Async(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Response> UtlevererWebService_m9_3Async(NettapotekForm.UtlevererWebService.M9_3 M9_3Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m9_3Request();
            inValue.M9_3Element = M9_3Element;
            return ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m9_3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Response NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m9_21(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Request request) {
            return base.Channel.UtlevererWebService_m9_21(request);
        }
        
        public NettapotekForm.UtlevererWebService.M9_22 UtlevererWebService_m9_21(NettapotekForm.UtlevererWebService.M9_21 M9_21Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Request();
            inValue.M9_21Element = M9_21Element;
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Response retVal = ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m9_21(inValue);
            return retVal.M9_22Element;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Response> NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m9_21Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Request request) {
            return base.Channel.UtlevererWebService_m9_21Async(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Response> UtlevererWebService_m9_21Async(NettapotekForm.UtlevererWebService.M9_21 M9_21Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m9_21Request();
            inValue.M9_21Element = M9_21Element;
            return ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m9_21Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Response NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m9_1(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Request request) {
            return base.Channel.UtlevererWebService_m9_1(request);
        }
        
        public NettapotekForm.UtlevererWebService.M9_2 UtlevererWebService_m9_1(NettapotekForm.UtlevererWebService.M9_1 M9_1Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Request();
            inValue.M9_1Element = M9_1Element;
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Response retVal = ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m9_1(inValue);
            return retVal.M9_2Element;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Response> NettapotekForm.UtlevererWebService.UtlevererWeb.UtlevererWebService_m9_1Async(NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Request request) {
            return base.Channel.UtlevererWebService_m9_1Async(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Response> UtlevererWebService_m9_1Async(NettapotekForm.UtlevererWebService.M9_1 M9_1Element) {
            NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Request inValue = new NettapotekForm.UtlevererWebService.UtlevererWebService_m9_1Request();
            inValue.M9_1Element = M9_1Element;
            return ((NettapotekForm.UtlevererWebService.UtlevererWeb)(this)).UtlevererWebService_m9_1Async(inValue);
        }
    }
}
