//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;

namespace NettapotekForm.NettapotekWebService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/")]
    public partial class AppRecFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/")]
    public partial class M9na2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/")]
    public partial class M9na1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/")]
    public partial class M9na4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/")]
    public partial class M9na3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/types/", Order=0)]
        public object dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/", ConfigurationName="NettapotekWebService.NAWeb")]
    public interface NAWeb {
        
        // CODEGEN: Generating message contract since the operation NAWebService_m9na3 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="M9na3", ReplyAction="http://na.webservices.reseptformidleren.ergo.no/NAWeb/NAWebService_m9na3Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(NettapotekForm.NettapotekWebService.AppRecFault), Action="http://na.webservices.reseptformidleren.ergo.no/NAWeb/NAWebService_m9na3/Fault/Ap" +
            "pRecFault", Name="AppRecFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9na2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9na1))]
        NettapotekForm.NettapotekWebService.NAWebService_m9na3Response NAWebService_m9na3(NettapotekForm.NettapotekWebService.NAWebService_m9na3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="M9na3", ReplyAction="http://na.webservices.reseptformidleren.ergo.no/NAWeb/NAWebService_m9na3Response")]
        System.Threading.Tasks.Task<NettapotekForm.NettapotekWebService.NAWebService_m9na3Response> NAWebService_m9na3Async(NettapotekForm.NettapotekWebService.NAWebService_m9na3Request request);
        
        // CODEGEN: Generating message contract since the operation NAWebService_m9na1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="M9na1", ReplyAction="http://na.webservices.reseptformidleren.ergo.no/NAWeb/NAWebService_m9na1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(NettapotekForm.NettapotekWebService.AppRecFault), Action="http://na.webservices.reseptformidleren.ergo.no/NAWeb/NAWebService_m9na1/Fault/Ap" +
            "pRecFault", Name="AppRecFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9na2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(M9na1))]
        NettapotekForm.NettapotekWebService.NAWebService_m9na1Response NAWebService_m9na1(NettapotekForm.NettapotekWebService.NAWebService_m9na1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="M9na1", ReplyAction="http://na.webservices.reseptformidleren.ergo.no/NAWeb/NAWebService_m9na1Response")]
        System.Threading.Tasks.Task<NettapotekForm.NettapotekWebService.NAWebService_m9na1Response> NAWebService_m9na1Async(NettapotekForm.NettapotekWebService.NAWebService_m9na1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NAWebService_m9na3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.NettapotekWebService.M9na3 M9na3Element;
        
        public NAWebService_m9na3Request() {
        }
        
        public NAWebService_m9na3Request(NettapotekForm.NettapotekWebService.M9na3 M9na3Element) {
            this.M9na3Element = M9na3Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NAWebService_m9na3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.NettapotekWebService.M9na4 M9na4Element;
        
        public NAWebService_m9na3Response() {
        }
        
        public NAWebService_m9na3Response(NettapotekForm.NettapotekWebService.M9na4 M9na4Element) {
            this.M9na4Element = M9na4Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NAWebService_m9na1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.NettapotekWebService.M9na1 M9na1Element;
        
        public NAWebService_m9na1Request() {
        }
        
        public NAWebService_m9na1Request(NettapotekForm.NettapotekWebService.M9na1 M9na1Element) {
            this.M9na1Element = M9na1Element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NAWebService_m9na1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://na.webservices.reseptformidleren.ergo.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NettapotekForm.NettapotekWebService.M9na2 M9na2Element;
        
        public NAWebService_m9na1Response() {
        }
        
        public NAWebService_m9na1Response(NettapotekForm.NettapotekWebService.M9na2 M9na2Element) {
            this.M9na2Element = M9na2Element;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NAWebChannel : NettapotekForm.NettapotekWebService.NAWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NAWebClient : System.ServiceModel.ClientBase<NettapotekForm.NettapotekWebService.NAWeb>, NettapotekForm.NettapotekWebService.NAWeb {
        
        public NAWebClient() {
        }
        
        public NAWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NAWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NAWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NAWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.NettapotekWebService.NAWebService_m9na3Response NettapotekForm.NettapotekWebService.NAWeb.NAWebService_m9na3(NettapotekForm.NettapotekWebService.NAWebService_m9na3Request request) {
            return base.Channel.NAWebService_m9na3(request);
        }
        
        public NettapotekForm.NettapotekWebService.M9na4 NAWebService_m9na3(NettapotekForm.NettapotekWebService.M9na3 M9na3Element) {
            NettapotekForm.NettapotekWebService.NAWebService_m9na3Request inValue = new NettapotekForm.NettapotekWebService.NAWebService_m9na3Request();
            inValue.M9na3Element = M9na3Element;
            NettapotekForm.NettapotekWebService.NAWebService_m9na3Response retVal = ((NettapotekForm.NettapotekWebService.NAWeb)(this)).NAWebService_m9na3(inValue);
            return retVal.M9na4Element;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.NettapotekWebService.NAWebService_m9na3Response> NettapotekForm.NettapotekWebService.NAWeb.NAWebService_m9na3Async(NettapotekForm.NettapotekWebService.NAWebService_m9na3Request request) {
            return base.Channel.NAWebService_m9na3Async(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.NettapotekWebService.NAWebService_m9na3Response> NAWebService_m9na3Async(NettapotekForm.NettapotekWebService.M9na3 M9na3Element) {
            NettapotekForm.NettapotekWebService.NAWebService_m9na3Request inValue = new NettapotekForm.NettapotekWebService.NAWebService_m9na3Request();
            inValue.M9na3Element = M9na3Element;
            return ((NettapotekForm.NettapotekWebService.NAWeb)(this)).NAWebService_m9na3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NettapotekForm.NettapotekWebService.NAWebService_m9na1Response NettapotekForm.NettapotekWebService.NAWeb.NAWebService_m9na1(NettapotekForm.NettapotekWebService.NAWebService_m9na1Request request) {
            return base.Channel.NAWebService_m9na1(request);
        }
        
        public NettapotekForm.NettapotekWebService.M9na2 NAWebService_m9na1(NettapotekForm.NettapotekWebService.M9na1 M9na1Element) {
            NettapotekForm.NettapotekWebService.NAWebService_m9na1Request inValue = new NettapotekForm.NettapotekWebService.NAWebService_m9na1Request();
            inValue.M9na1Element = M9na1Element;
            
            NettapotekForm.NettapotekWebService.NAWebService_m9na1Response retVal = ((NettapotekForm.NettapotekWebService.NAWeb)(this)).NAWebService_m9na1(inValue);
            
            return retVal.M9na2Element;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NettapotekForm.NettapotekWebService.NAWebService_m9na1Response> NettapotekForm.NettapotekWebService.NAWeb.NAWebService_m9na1Async(NettapotekForm.NettapotekWebService.NAWebService_m9na1Request request) {
            return base.Channel.NAWebService_m9na1Async(request);
        }
        
        public System.Threading.Tasks.Task<NettapotekForm.NettapotekWebService.NAWebService_m9na1Response> NAWebService_m9na1Async(NettapotekForm.NettapotekWebService.M9na1 M9na1Element) {
            NettapotekForm.NettapotekWebService.NAWebService_m9na1Request inValue = new NettapotekForm.NettapotekWebService.NAWebService_m9na1Request();
            inValue.M9na1Element = M9na1Element;
            return ((NettapotekForm.NettapotekWebService.NAWeb)(this)).NAWebService_m9na1Async(inValue);
        }
    }
}
